spring:
  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: ${DB_PLATFORM}
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp

  # File upload config
  servlet:
    multipart:
      max-file-size: ${MAX_UPLOAD_FILE_SIZE}
      max-request-size: ${MAX_UPLOAD_FILE_REQUEST_SIZE}

server:
  port: ${PORT:8080}

app:
  otp:
    expiry-minutes: ${OTP_EXPIRY_MIN:5}
    max-per-hour: ${OTP_MAX_PER_HOUR:6}
    resend-cooldown-seconds: ${OTP_RESEND_COOLDOWN_SEC:50}
    max-attempts: ${OTP_MAX_ATTEMPTS:5}

  mail:
    from: ${MAIL_FROM}

  jwt:
    secret: ${JWT_SECRET:}
    access-token-ttl: ${JWT_ACCESS_TOKEN_TTL:15m}
    refresh-token-ttl: ${JWT_REFRESH_TOKEN_TTL:30d}

  telegram:
    bot-token: ${TELEGRAM_BOT_TOKEN}
    chat-id: ${TELEGRAM_CHAT_ID}
    log-enable: ${TELEGRAM_LOG_ENABLE:false}

  upload:
    dir: ${UPLOAD_DIR:uploads}
    base-url: ${UPLOAD_BASE_URL:http://localhost:8080}

  # Cloudflare R2 config
  r2-properties:
    account-id: ${R2_ACCOUNT_ID}
    access-key: ${R2_ACCESS_KEY}
    secret-key: ${R2_SECRET_KEY}
    bucket-name: ${R2_BUCKET_NAME}
    public-url: ${R2_PUBLIC_URL}

  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:5173,http://localhost:3000,http://192.168.0.132:5173}

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE